In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("eksikveriler.csv")

In [3]:
df

ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

In [6]:
yas = df.iloc[:,3:4].values

In [7]:
yas

array([[10.],
       [11.],
       [10.],
       [ 9.],
       [12.],
       [30.],
       [25.],
       [35.],
       [22.],
       [33.],
       [27.],
       [44.],
       [nan],
       [41.],
       [55.],
       [47.],
       [nan],
       [27.],
       [28.],
       [29.],
       [32.],
       [42.]])

In [8]:
imputer = imputer.fit(yas)

In [9]:
yas = imputer.transform(yas)

In [10]:
yas

array([[10.  ],
       [11.  ],
       [10.  ],
       [ 9.  ],
       [12.  ],
       [30.  ],
       [25.  ],
       [35.  ],
       [22.  ],
       [33.  ],
       [27.  ],
       [44.  ],
       [28.45],
       [41.  ],
       [55.  ],
       [47.  ],
       [28.45],
       [27.  ],
       [28.  ],
       [29.  ],
       [32.  ],
       [42.  ]])

In [11]:
ulke = df.iloc[:,0:1].values

In [12]:
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [12]:
from sklearn import preprocessing

In [13]:
le = preprocessing.LabelEncoder()

In [14]:
ulke[:,0] = le.fit_transform(df.iloc[:,0])

In [15]:
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [33]:
ohe = preprocessing.OneHotEncoder()

In [34]:
ulke = ohe.fit_transform(ulke).toarray()

In [35]:
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [39]:
son = pd.DataFrame(data=ulke, columns=["fr","tr","us"])

In [44]:
son2 = pd.DataFrame(data=df.iloc[:,1:3], columns=["boy","kilo"])

In [45]:
son3 = pd.DataFrame(data=yas, columns=["yas"])

In [53]:
son4 = pd.DataFrame(data=df.iloc[:,-1], columns=["cinsiyet"])

In [54]:
sondf = pd.concat([son,son2,son3,son4], axis=1)

In [55]:
sondf

fr   tr   us  boy  kilo    yas cinsiyet
0   0.0  1.0  0.0  130    30  10.00        e
1   0.0  1.0  0.0  125    36  11.00        e
2   0.0  1.0  0.0  135    34  10.00        k
3   0.0  1.0  0.0  133    30   9.00        k
4   0.0  1.0  0.0  129    38  12.00        e
5   0.0  1.0  0.0  180    90  30.00        e
6   0.0  1.0  0.0  190    80  25.00        e
7   0.0  1.0  0.0  175    90  35.00        e
8   0.0  1.0  0.0  177    60  22.00        k
9   0.0  0.0  1.0  185   105  33.00        e
10  0.0  0.0  1.0  165    55  27.00        k
11  0.0  0.0  1.0  155    50  44.00        k
12  0.0  0.0  1.0  160    58  28.45        k
13  0.0  0.0  1.0  162    59  41.00        k
14  0.0  0.0  1.0  167    62  55.00        k
15  1.0  0.0  0.0  174    70  47.00        e
16  1.0  0.0  0.0  193    90  28.45        e
17  1.0  0.0  0.0  187    80  27.00        e
18  1.0  0.0  0.0  183    88  28.00        e
19  1.0  0.0  0.0  159    40  29.00        k
20  1.0  0.0  0.0  164    66  32.00        k
21  1.0  0.0  0.0  166    56  42.00        k

In [59]:
y = sondf["cinsiyet"].values
x = sondf.drop(["cinsiyet"], axis=1).values

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=19)

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler = StandardScaler()

In [65]:
x_train = scaler.fit_transform(x_train)

In [66]:
x_test = scaler.transform(x_test)